spring:
  liquibase:
    contexts: docker

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    liquibase: info
    '[by.arvisit.modsenlibapp.libraryservice]': debug
    '[org.springframework.security]': debug
    '[org.springframework.web]': debug
