spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
    cors:
      allowedOrigin: ${CORS_ALLOWED_ORIGIN}
      allowedMethod: ${CORS_ALLOWED_METHOD}
      allowedHeader: ${CORS_ALLOWED_HEADER}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true

springdoc:
  api-docs:
    path: /modsen-security-service/v3/api-docs
  swagger-ui:
    path: /modsen-security-service/swagger-ui.html

server:
  port: 8082
